### ISSUE TITLE
Command gitlabSnippets.addhost not found

### ISSUE THREAD

**Issue by pseudomix** [JennieJi/vsext-gitlab-snippets#23] opened 2022-10-15 10:37 UTC
Hello,
I'm triying to use this Extension but i face this issue:
Command 'gitlabSnippets.addHost' not found when i try to add my Gitlab Instance using the Command Palette

May i have missed something ?
Please help.
Thanks

**Comment by JennieJi** [comment] 2022-10-16 22:05
Let me find a chance to try whether I can reproduce.

In the meantime, could you try install an older version to try again?

**Comment by pseudomix** [comment] 2022-10-17 12:33
I tried with 0.0.3, 0.1.0, 0.2.0 and 0.2.1 but same issue.
I tried with fresh VSC portable version with no other extensions same issue.
I tried on 2 computers but same thing.

The other command fails with the same message.

I'm with Windows 11 (french language). 

Hope it will help

**Comment by JennieJi** [comment] 2022-10-24 05:09
Hi @pseudomix I found VSCode extension may have changed its way to initializing the extension. Hence my extension no longer worked without bundling everything when publish. 

Could you help to try the latest `v0.2.3`? It works for me now.

**Comment by pseudomix** [comment] 2022-10-26 06:32
Hi, it's working now! Thanks Jennie !
Have a nice day

**Comment by JennieJi** [comment] 2022-10-27 04:22
Fixed in [ e7afbb8133d38f79a153d97dbd4576f22660156b](https://github.com/JennieJi/vsext-gitlab-snippets/releases/tag/v0.2.3)

**Closed as completed by JennieJi** 2022-10-27 04:22 UTC
